baseURL = 'https://charliedyson.net/'
languageCode = 'en'
title = 'charliedyson.net'
theme="manis"
publishDir = "build"

[permalinks]
    blog = "blog/:year/:month/:filename/"


[params]
    tagline = "Some thinkings"
    dateFmt = "02 Jan 2006"

    utterancesRepo = "cdyson37/cdyson37.github.io"
    utterancesTheme = "github-light"
    utterancesLabel = "utterance"
    utterancesSections = [ "blog" ]

    colorTheme = "#ff6565"

    email = "charlie@charliedyson.net"
    linkedin = "https://www.linkedin.com/in/charlie-dyson-a701a31a5"
    github = "https://github.com/cdyson37"
